server:
  port: 9900
    
  
spring:
  application:
    name: My-API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: CATALOG-SERVICE
        uri: lb://CATALOG-SERVICE
        predicates:
        - Path= /products/**
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path= /orders/**
      - id: INVENTORY-SERVICE
        uri: lb://INVENTORY-SERVICE
        predicates:
        - Path= /code/**
             
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

